### ISSUE TITLE
Python bindings on Fedora: undefined symbol: _ZTIN3vrv12AttFacsimileE

### ISSUE THREAD

**Issue by musicog** [rism-ch/verovio#1121]
I compiled a freshly cloned Verovio and attempted to install the Python bindings as per the build instructions. 

OS: Fedora Linux 30 
Verovio version:  latest develop branch (commit adc68a5e8)

The installation process appears to work fine, but when I attempt to import verovio in Python I get:

```
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import verovio
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/verovio-2.0.0-py3.7-linux-x86_64.egg/verovio.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib64/python3.7/site-packages/verovio-2.0.0-py3.7-linux-x86_64.egg/_verovio.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3vrv12AttFacsimileE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/verovio-2.0.0-py3.7-linux-x86_64.egg/verovio.py", line 17, in <module>
    _verovio = swig_import_helper()
  File "/usr/local/lib64/python3.7/site-packages/verovio-2.0.0-py3.7-linux-x86_64.egg/verovio.py", line 16, in swig_import_helper
    return importlib.import_module('_verovio')
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib64/python3.7/site-packages/verovio-2.0.0-py3.7-linux-x86_64.egg/_verovio.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3vrv12AttFacsimileE
```
N.b. I tried installing and then importing using both Python 2 and 3, and get the same problem on each. 

Seems related to att.facsimile, and possibly to older issues of undefined symbols (e.g. [294](https://github.com/rism-ch/verovio/issues/294), [603](https://github.com/rism-ch/verovio/issues/603))?

Any hints appreciated. Apologies if I've missed something obvious!

**Comment by mjwalter** [comment]
I have been having the same problem on MacOS Mojave the past two days.

**Comment by mjwalter** [comment]
I switched to the `master` branch and am not having this problem. It looks like there is a bug in the `develop` branch.

**Comment by musicog** [comment]
I swear I tried that yesterday to no avail, but I must have made a mistake then -- perhaps a python2 / 3 confusion (rebuilding for 3 but testing in 2, or some similar stupidity).

Anyway, master does indeed work. Thanks!! 

It must be a bug in develop.

**Comment by lpugin** [comment]
Should be fixed with this 939bdd41b28a8fe20f1d886c3574ffe7434b389f Please double check

**Comment by musicog** [comment]
Sorry to say that this now doesn't compile - I think it's missing some constants in editortoolkit_neume.cpp.

Excerpt from output of `python3 setup.py build_ext` (happy to provide full log if helpful...)

```
./../src/editortoolkit_neume.cpp:770:15: error: ‘INT_MAX’ was not declared in this scope
  770 |     int ulx = INT_MAX, uly = 0, lrx = 0, lry = 0;
      |               ^~~~~~~
../../src/editortoolkit_neume.cpp:33:1: note: ‘INT_MAX’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
   32 | #include "vrv.h"
  +++ |+#include <climits>
   33 |
../../src/editortoolkit_neume.cpp:779:13: error: ‘lrx’ was not declared in this scope
  779 |             lrx = lrx > zone->GetLrx() ? lrx : zone->GetLrx();
      |             ^~~
../../src/editortoolkit_neume.cpp:780:13: error: ‘uly’ was not declared in this scope; did you mean ‘ulx’?
  780 |             uly += zone->GetUly();
      |             ^~~
      |             ulx
../../src/editortoolkit_neume.cpp:781:13: error: ‘lry’ was not declared in this scope
  781 |             lry += zone->GetLry();
      |             ^~~
../../src/editortoolkit_neume.cpp:793:5: error: ‘uly’ was not declared in this scope; did you mean ‘ulx’?
  793 |     uly /= staves.size();
      |     ^~~
      |     ulx
../../src/editortoolkit_neume.cpp:794:5: error: ‘lry’ was not declared in this scope
  794 |     lry /= staves.size();
      |     ^~~
../../src/editortoolkit_neume.cpp:816:23: error: ‘lrx’ was not declared in this scope
  816 |     staffZone->SetLrx(lrx);
      |                       ^~~
error: command 'gcc' failed with exit status 1
```

**Comment by lpugin** [comment]
Travis is now happy: https://travis-ci.org/rism-ch/verovio/jobs/557269957 Hopefully it is properly fixed.

**Comment by musicog** [comment]
Sorry, now builds but causes another problem on import :-(

Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import verovio
Traceback (most recent call last):
  File "/home/weigl/repos/verovio/bindings/python/verovio.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib64/python3.7/site-packages/verovio-2.0.0-py3.7-linux-x86_64.egg/_verovio.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3vrv9AttNcFormE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weigl/repos/verovio/bindings/python/verovio.py", line 17, in <module>
    _verovio = swig_import_helper()
  File "/home/weigl/repos/verovio/bindings/python/verovio.py", line 16, in swig_import_helper
    return importlib.import_module('_verovio')
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib64/python3.7/site-packages/verovio-2.0.0-py3.7-linux-x86_64.egg/_verovio.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3vrv9AttNcFormE
>>>

**Comment by mjwalter** [comment]
@musicog You may find it helpful to delete your old installation and reclone the repository.

**Comment by lpugin** [comment]
@mjwalter is it fixed for you?

**Comment by mjwalter** [comment]
@lpugin Yes, it is working fine on the current develop branch for me!

**Comment by musicog** [comment]
Sorry, I was away on leave over an extended weekend. Just to confirm, now works for me as well! (after a clean reclone as per @mjwalter's suggestion)

Thanks for the quick fixes!
