### ISSUE TITLE
Emscripten build breaks unpredictably on some GH action runs

### ISSUE THREAD

**Issue by musicEnfanthen** [rism-ch/verovio#1767]
For some build workflow runs, it seems that the emscripten config changes and clears the cache while running the build:

```
  shared:INFO: (Emscripten: Running sanity checks)
  [  4%] Building CXX object CMakeFiles/verovio.dir/home/runner/work/verovio/verovio/src/arpeg.cpp.o
  [  5%] Building CXX object CMakeFiles/verovio.dir/home/runner/work/verovio/verovio/src/artic.cpp.o
shared:INFO: (Emscripten: config changed, clearing cache)
shared:INFO: (Emscripten: config changed, clearing cache)
shared:INFO: (Emscripten: Running sanity checks)
  [  5%] Building CXX object CMakeFiles/verovio.dir/home/runner/work/verovio/verovio/src/att.cpp.o
Traceback (most recent call last):
  File "/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/em++.py", line 14, in <module>
  sys.exit(emcc.run(sys.argv))
  File "/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/emcc.py", line 753, in run
  shared.check_sanity(force=DEBUG)
  File "/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/tools/shared.py", line 599, in check_sanity
  Cache.erase()
  File "/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/tools/cache.py", line 81, in erase
  self.acquire_cache_lock()
  File "/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/tools/cache.py", line 54, in acquire_cache_lock
  self.filelock.acquire(60)
  File "/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/tools/filelock.py", line 240, in acquire
  self._acquire()
  File "/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/tools/filelock.py", line 360, in _acquire
  fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/verovio/verovio/emsdk-cache-310513115/emsdk-master/upstream/emscripten/cache/wasm/cache.lock
```
Finally, the build job fails.

Hint to an underlying issue: https://github.com/WebAssembly/waterfall/issues/331:

> The sanity check process in emscripten thinks current cache is invalid when 'sanity file's mtime <= config file's mtime'.

See also https://github.com/emscripten-core/emscripten/pull/3057#issuecomment-66216735

**Comment by lpugin** [comment]
Looks good now. Thanks!
