### ISSUE TITLE
Python fails to import verovio module

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#294]
Simple example:

```python
import verovio
```

Result:
```
Traceback (most recent call last):
  File "/home/simon/test.py", line 1, in <module>
    import verovio
  File "/usr/local/lib/python3.5/dist-packages/verovio.py", line 28, in <module>
    _verovio = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/verovio.py", line 24, in swig_import_helper
    _mod = imp.load_module('_verovio', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/_verovio.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3vrv12AttMiditempoE
```

The used version is recently downloaded from GitHub and compiled according to the instructions in the wiki.

**Comment by lpugin** [comment]
Fixed ab93b2d662f780dcf8601d9b78951a3686a613c6

**Comment by sonovice** [comment]
The error is back on the develop branch.

**Comment by craigsapp** [comment]
I just tried it in OS X, and was sucessful, creating:
```
dist/verovio-0.9.12-py2.7-macosx-10.9-x86_64.egg
```

The problem you are having seems to indicate that `libmei/atts_midi.cpp` is not being compiled or found.  It should be included in this list in `./python/setup.py`:

```cpp
     sources=
        glob('../src/*.cpp') +
        [
             '../src/json/jsonxx.cc',
             '../src/pugi/pugixml.cpp',
             '../src/midi/Binasc.cpp',
             '../src/midi/MidiEvent.cpp',
             '../src/midi/MidiEventList.cpp',
             '../src/midi/MidiFile.cpp',
             '../src/midi/MidiMessage.cpp',
             '../src/hum/humlib.cpp',
             '../libmei/attconverter.cpp',
             '../libmei/atts_cmn.cpp',
             '../libmei/atts_critapp.cpp',
             '../libmei/atts_mei.cpp',
             '../libmei/atts_mensural.cpp',
             '../libmei/atts_midi.cpp',
             '../libmei/atts_pagebased.cpp',
             '../libmei/atts_shared.cpp',
             'verovio.i'],
```

if the file is not listed there, then you may need to pull the most recent version of the `develop` branch. 

Or you may need to clean out old compiled object files in order to force file(s) to be recompiled, which I do not see how to do automatically.  In that case, try deleting all files/directories in the `python` directory except for `setup.py` and `verovio.i`.

**Comment by sonovice** [comment]
Sorry, my bad. I had some old files that were referenced despite having the latest version.
